import crypto from "node:crypto";
import { getWorkspaceStore } from "@/lib/db";
export type OAuthProvider = "ghl" | "zapier" | "make";

const baseUrl = () => process.env.NEXT_PUBLIC_APP_URL || process.env.APP_URL || "http://localhost:3000";
export const providerConfig: Record<OAuthProvider, { label: string; authorizeUrl: string; tokenUrl: string; scopes: string }> = {
  ghl: { label: "HighLevel", authorizeUrl: process.env.GHL_AUTHORIZE_URL || "https://marketplace.gohighlevel.com/oauth/chooselocation", tokenUrl: "https://services.leadconnectorhq.com/oauth/token", scopes: process.env.GHL_OAUTH_SCOPES || "contacts.readonly locations.readonly" },
  zapier: { label: "Zapier", authorizeUrl: "https://api.zapier.com/v2/authorize", tokenUrl: "https://zapier.com/oauth/token/", scopes: process.env.ZAPIER_OAUTH_SCOPES || "profile zap:all" },
  make: { label: "Make", authorizeUrl: "https://www.make.com/oauth/v2/authorize", tokenUrl: "https://www.make.com/oauth/v2/token", scopes: process.env.MAKE_OAUTH_SCOPES || "openid scenarios:read organization:read user:read teams:read" },
};
function envName(provider: OAuthProvider, key: "CLIENT_ID" | "CLIENT_SECRET") { return `${provider.toUpperCase()}_${key}`; }
export function callbackUrl(provider: OAuthProvider) { return process.env[`${provider.toUpperCase()}_REDIRECT_URI`] || `${baseUrl()}/api/oauth/${provider}/callback`; }
export function oauthConfigured(provider: OAuthProvider) { return Boolean(process.env[envName(provider, "CLIENT_ID")] && process.env[envName(provider, "CLIENT_SECRET")]); }
export async function createState(provider: OAuthProvider) { const state = crypto.randomBytes(32).toString("hex"); const store = await getWorkspaceStore(); await store.oauthStates.create({ state, provider, expiresAt: new Date(Date.now()+10*60_000).toISOString() }); return state; }
export function buildAuthorizationUrl(provider: OAuthProvider, state: string) { const config=providerConfig[provider]; const url=new URL(config.authorizeUrl); url.searchParams.set("response_type","code"); url.searchParams.set("client_id",process.env[envName(provider,"CLIENT_ID")]!); url.searchParams.set("redirect_uri",callbackUrl(provider)); url.searchParams.set("scope",config.scopes); url.searchParams.set("state",state); if(provider==="zapier") url.searchParams.set("response_mode","query"); return url.toString(); }
async function parseJson(response: Response) { const text=await response.text(); let body:any={}; try{body=text?JSON.parse(text):{}}catch{body={raw:text}} if(!response.ok) throw new Error(`${response.status}: ${body.error_description||body.error||body.message||"OAuth request failed"}`); return body; }
function encryptionKey(){const raw=process.env.OUTCOM_TOKEN_ENCRYPTION_KEY;if(!raw||!/^[0-9a-fA-F]{64}$/.test(raw))throw new Error("OUTCOM_TOKEN_ENCRYPTION_KEY must be a 64-character hex key");return Buffer.from(raw,"hex")}
export function encryptSecret(value:string){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv("aes-256-gcm",encryptionKey(),iv);const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`}
export function decryptSecret(value:string){const [ivRaw,tagRaw,dataRaw]=value.split(".");const decipher=crypto.createDecipheriv("aes-256-gcm",encryptionKey(),Buffer.from(ivRaw,"base64url"));decipher.setAuthTag(Buffer.from(tagRaw,"base64url"));return Buffer.concat([decipher.update(Buffer.from(dataRaw,"base64url")),decipher.final()]).toString("utf8")}
export async function exchangeCode(provider:OAuthProvider,code:string){const c=providerConfig[provider],clientId=process.env[envName(provider,"CLIENT_ID")]!,clientSecret=process.env[envName(provider,"CLIENT_SECRET")]!,body=new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:callbackUrl(provider)});let response:Response;if(provider==="zapier"){response=await fetch(c.tokenUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Authorization:`Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`},body})}else{body.set("client_id",clientId);body.set("client_secret",clientSecret);if(provider==="ghl")body.set("user_type","Location");response=await fetch(c.tokenUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body})}return parseJson(response)}
export async function refreshAccessToken(provider:OAuthProvider,refreshToken:string){const c=providerConfig[provider],clientId=process.env[envName(provider,"CLIENT_ID")]!,clientSecret=process.env[envName(provider,"CLIENT_SECRET")]!,body=new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken});let response:Response;if(provider==="zapier"){response=await fetch(c.tokenUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Authorization:`Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`},body})}else{body.set("client_id",clientId);body.set("client_secret",clientSecret);response=await fetch(c.tokenUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body})}return parseJson(response)}
export async function getValidAccessToken(provider:OAuthProvider){const store=await getWorkspaceStore();const connection=await store.connections.latest(provider);if(!connection)return null;if(connection.expiresAt&&new Date(connection.expiresAt).getTime()>Date.now()+60_000)return decryptSecret(connection.accessToken);if(!connection.refreshToken)return decryptSecret(connection.accessToken);const tokens=await refreshAccessToken(provider,decryptSecret(connection.refreshToken));await store.connections.updateTokens(connection.id,{accessToken:encryptSecret(tokens.access_token),refreshToken:tokens.refresh_token?encryptSecret(tokens.refresh_token):connection.refreshToken,expiresAt:tokens.expires_in?new Date(Date.now()+Number(tokens.expires_in)*1000).toISOString():null});return tokens.access_token as string}
async function discoverMakeBaseUrl(accessToken:string){const configured=String(process.env.MAKE_API_BASE_URL||"").replace(/\/$/,"");const zones=String(process.env.MAKE_API_ZONES||"eu1,eu2,us1,us2").split(",").map(x=>x.trim()).filter(Boolean);const candidates=[configured,...zones.map(zone=>`https://${zone}.make.com/api/v2`)].filter(Boolean);for(const base of [...new Set(candidates)]){for(const scheme of ["Bearer","Token"]){try{const r=await fetch(`${base}/users/me?cols[]=id&cols[]=name&cols[]=email&cols[]=userTeamRoles`,{headers:{Authorization:`${scheme} ${accessToken}`,Accept:"application/json"},cache:"no-store"});if(r.ok)return base}catch{}}}return configured||null}
export async function profileFor(provider:OAuthProvider,accessToken:string,tokenPayload:any){
 if(provider==="zapier"){const r=await fetch("https://api.zapier.com/v1/profiles/me",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});const p=await parseJson(r);const x=Array.isArray(p)?p[0]:p;return{accountId:String(x?.id??tokenPayload.user_id??crypto.randomUUID()),accountName:x?.full_name||x?.email||"Zapier account",email:x?.email||null,metadata:{timezone:x?.timezone}}}
 if(provider==="make"){const base=await discoverMakeBaseUrl(accessToken);if(!base)throw new Error("Make connected, but Outcom could not determine the Make API region for this account.");const [oidc,me]=await Promise.all([fetch("https://www.make.com/oauth/v2/oidc/userinfo",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"}).then(parseJson),fetch(`${base}/users/me?cols[]=id&cols[]=name&cols[]=email&cols[]=userOrganizationRoles&cols[]=userTeamRoles`,{headers:{Authorization:`Bearer ${accessToken}`,Accept:"application/json"},cache:"no-store"}).then(parseJson).catch(()=>({}))]);const user=me.authUser||me.user||me;const roles=Array.isArray(user.userTeamRoles)?user.userTeamRoles:[];const orgRoles=Array.isArray(user.userOrganizationRoles)?user.userOrganizationRoles:[];return{accountId:String(oidc.sub||user.id||crypto.randomUUID()),accountName:oidc.name||user.name||oidc.email||user.email||"Make account",email:oidc.email||user.email||null,metadata:{organizationId:roles[0]?.organizationId||orgRoles[0]?.organizationId||null,teamId:roles[0]?.teamId||null,userId:user.id||oidc.sub||null,userTeamRoles:roles,baseUrl:base,authMode:"oauth"}}}
 const locationId=tokenPayload.locationId||tokenPayload.companyId||crypto.randomUUID();let accountName=`HighLevel location ${locationId}`;try{const r=await fetch(`https://services.leadconnectorhq.com/locations/${encodeURIComponent(locationId)}`,{headers:{Authorization:`Bearer ${accessToken}`,Version:"v3",Accept:"application/json"},cache:"no-store"});const p=await parseJson(r);accountName=p.location?.name||accountName}catch{}return{accountId:String(locationId),accountName,email:null,metadata:{companyId:tokenPayload.companyId,userId:tokenPayload.userId,userType:tokenPayload.userType,approvedLocations:tokenPayload.approvedLocations||[]}}
}
